# Generated by Django 4.1.7 on 2023-05-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('phn_no', models.IntegerField(blank=True, null=True)),
                ('msg', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
