# Generated by Django 4.1.7 on 2023-04-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
