# Generated by Django 4.1.7 on 2023-04-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_nme', models.CharField(blank=True, max_length=50, null=True)),
                ('a_nme', models.CharField(blank=True, max_length=50, null=True)),
                ('pri', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
