# Generated by Django 4.1.7 on 2023-05-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=20, null=True)),
                ('c_img', models.ImageField(blank=True, null=True, upload_to='category_img')),
                ('c_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
