# Generated by Django 4.1.7 on 2023-04-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(blank=True, max_length=50, null=True)),
                ('add', models.CharField(blank=True, max_length=100, null=True)),
                ('mob', models.IntegerField(blank=True, null=True)),
                ('em', models.CharField(blank=True, max_length=50, null=True)),
                ('cour', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
