# Generated by Django 4.1.7 on 2023-04-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nme', models.CharField(blank=True, max_length=20, null=True)),
                ('mobi', models.IntegerField(blank=True, null=True)),
                ('ema', models.EmailField(blank=True, max_length=40, null=True)),
                ('comp', models.CharField(blank=True, max_length=20, null=True)),
                ('sal', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='emp_pic')),
            ],
        ),
    ]
