# Generated by Django 4.1.7 on 2023-04-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_reg',
            name='gender',
        ),
    ]
