# Generated by Django 4.1.7 on 2023-04-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_temp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='imge',
        ),
    ]
