# Generated by Django 4.1.7 on 2023-04-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_temp', '0002_rename_image_student_imge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=20, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('institute', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='institute')),
            ],
        ),
    ]
